const EMERGENCY_PHRASES={
medical:{
 zh:"我受傷了，需要醫療協助。",
 en:"I’m injured and need medical assistance.",
 ja:"けがをしています。医療の助けが必要です。",
 ko:"다쳤습니다. 의료 도움이 필요합니다.",
 vi:"Tôi bị thương và cần được hỗ trợ y tế.",
 th:"ฉันได้รับบาดเจ็บและต้องการความช่วยเหลือทางการแพทย์",
 ms:"Saya cedera dan memerlukan bantuan perubatan.",
 fil:"Nasugatan ako at kailangan ko ng tulong medikal.",
 id:"Saya terluka dan membutuhkan bantuan medis.",
 de:"Ich bin verletzt und brauche medizinische Hilfe.",
 fr:"Je suis blessé(e) et j’ai besoin d’une assistance médicale.",
 es:"Estoy herido/a y necesito asistencia médica.",
 yue:"我受咗傷，需要醫療協助。"
},
crime:{
 zh:"我遇到搶劫或攻擊，請幫我報警。",
 en:"I’ve been robbed or attacked. Please call the police.",
 ja:"強盗または暴行に遭いました。警察を呼んでください。",
 ko:"강도나 공격을 당했습니다. 경찰을 불러 주세요.",
 vi:"Tôi bị cướp hoặc bị tấn công. Xin hãy gọi cảnh sát giúp tôi.",
 th:"ฉันถูกปล้นหรือถูกทำร้าย กรุณาโทรเรียกตำรวจให้ฉันด้วย",
 ms:"Saya telah dirompak atau diserang. Tolong hubungi polis.",
 fil:"Ninakawan o inatake ako. Pakitawag ang pulis.",
 id:"Saya dirampok atau diserang. Tolong hubungi polisi.",
 de:"Ich wurde ausgeraubt oder angegriffen. Bitte rufen Sie die Polizei.",
 fr:"J’ai été victime d’un vol ou d’une agression. Appelez la police, s’il vous plaît.",
 es:"Me han robado o agredido. Por favor, llame a la policía.",
 yue:"我畀人打劫或者襲擊，請幫我報警。"
},
followed:{
 zh:"我被跟蹤，我現在感到不安全。",
 en:"Someone is following me and I don’t feel safe.",
 ja:"誰かにつけられています。身の危険を感じています。",
 ko:"누군가 저를 따라오고 있어서 안전하지 않다고 느낍니다.",
 vi:"Có người đang theo dõi tôi và tôi cảm thấy không an toàn.",
 th:"มีคนกำลังตามฉันมา และฉันรู้สึกไม่ปลอดภัย",
 ms:"Seseorang sedang mengekori saya dan saya berasa tidak selamat.",
 fil:"May sumusunod sa akin at pakiramdam ko ay hindi ako ligtas.",
 id:"Seseorang sedang mengikuti saya dan saya merasa tidak aman.",
 de:"Jemand verfolgt mich, und ich fühle mich nicht sicher.",
 fr:"Quelqu’un me suit et je ne me sens pas en sécurité.",
 es:"Alguien me está siguiendo y no me siento seguro/a.",
 yue:"有人跟住我，我而家覺得唔安全。"
},
accident:{
 zh:"發生事故了，請協助叫救護車或警察。",
 en:"There has been an accident. Please call an ambulance or the police.",
 ja:"事故が起きました。救急車か警察を呼んでください。",
 ko:"사고가 났습니다. 구급차나 경찰을 불러 주세요.",
 vi:"Đã xảy ra tai nạn. Xin hãy gọi xe cấp cứu hoặc cảnh sát.",
 th:"เกิดอุบัติเหตุ กรุณาโทรเรียกรถพยาบาลหรือตำรวจ",
 ms:"Kemalangan telah berlaku. Tolong hubungi ambulans atau polis.",
 fil:"May nangyaring aksidente. Pakitawag ang ambulansya o pulis.",
 id:"Terjadi kecelakaan. Tolong hubungi ambulans atau polisi.",
 de:"Es gab einen Unfall. Bitte rufen Sie einen Krankenwagen oder die Polizei.",
 fr:"Il y a eu un accident. Appelez une ambulance ou la police, s’il vous plaît.",
 es:"Ha ocurrido un accidente. Por favor, llame a una ambulancia o a la policía.",
 yue:"發生咗意外，請幫我叫救護車或者報警。"
},
passport:{
 zh:"我的護照遺失或被偷了，需要協助。",
 en:"My passport is lost or has been stolen. I need help.",
 ja:"パスポートを紛失したか、盗まれました。助けが必要です。",
 ko:"여권을 잃어버렸거나 도난당했습니다. 도움이 필요합니다.",
 vi:"Tôi bị mất hộ chiếu hoặc hộ chiếu đã bị đánh cắp. Tôi cần được giúp đỡ.",
 th:"หนังสือเดินทางของฉันหายหรือถูกขโมย ฉันต้องการความช่วยเหลือ",
 ms:"Pasport saya hilang atau telah dicuri. Saya perlukan bantuan.",
 fil:"Nawala o ninakaw ang pasaporte ko. Kailangan ko ng tulong.",
 id:"Paspor saya hilang atau dicuri. Saya membutuhkan bantuan.",
 de:"Mein Reisepass ist verloren gegangen oder wurde gestohlen. Ich brauche Hilfe.",
 fr:"Mon passeport est perdu ou a été volé. J’ai besoin d’aide.",
 es:"He perdido mi pasaporte o me lo han robado. Necesito ayuda.",
 yue:"我本護照唔見咗或者畀人偷咗，我需要協助。"
},
disaster:{
 zh:"這裡發生災害或重大事件，請告訴我安全避難方向。",
 en:"There is a disaster or major emergency. Please tell me where I can evacuate safely.",
 ja:"災害または重大な緊急事態が発生しています。安全に避難できる場所を教えてください。",
 ko:"재난이나 중대한 비상 상황이 발생했습니다. 안전하게 대피할 수 있는 곳을 알려 주세요.",
 vi:"Đang có thiên tai hoặc tình trạng khẩn cấp nghiêm trọng. Xin hãy chỉ cho tôi nơi sơ tán an toàn.",
 th:"กำลังเกิดภัยพิบัติหรือเหตุฉุกเฉินร้ายแรง กรุณาบอกฉันว่าควรอพยพไปที่ไหนจึงจะปลอดภัย",
 ms:"Sedang berlaku bencana atau kecemasan besar. Tolong beritahu saya tempat yang selamat untuk berpindah.",
 fil:"May sakuna o malubhang emerhensiya. Pakisabi kung saan ako maaaring lumikas nang ligtas.",
 id:"Sedang terjadi bencana atau keadaan darurat besar. Tolong beri tahu saya tempat evakuasi yang aman.",
 de:"Es gibt eine Katastrophe oder einen schweren Notfall. Bitte sagen Sie mir, wohin ich mich sicher evakuieren kann.",
 fr:"Il y a une catastrophe ou une urgence majeure. Indiquez-moi, s’il vous plaît, où je peux évacuer en toute sécurité.",
 es:"Hay un desastre o una emergencia grave. Por favor, dígame dónde puedo evacuar de forma segura.",
 yue:"呢度發生災害或者重大緊急事故，請話畀我知去邊度避難先安全。"
}
};
window.EMERGENCY_PHRASES=EMERGENCY_PHRASES;
