
const LiveEvents={
 timer:null,
 start(){this.refresh();clearInterval(this.timer);this.timer=setInterval(()=>this.refresh(),120000);window.addEventListener("state-changed",e=>{if(["manual","gps-ok","reverse-ok"].includes(e.detail.reason))this.refresh()});document.getElementById("refreshLive")?.addEventListener("click",()=>this.refresh())},
 async getJson(url,ms=4500){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{cache:"no-store",signal:c.signal});clearTimeout(t);if(!r.ok)throw new Error("http");return await r.json()}catch(e){clearTimeout(t);throw e}},
 async weather(){const s=StateCore.get();try{const j=await this.getJson(`https://api.open-meteo.com/v1/forecast?latitude=${s.lat}&longitude=${s.lon}&current=temperature_2m,apparent_temperature,precipitation,weather_code,wind_speed_10m&timezone=auto`,4500),c=j.current||{};RiskEngine.weather={temp:c.temperature_2m,feel:c.apparent_temperature,rain:c.precipitation,wind:c.wind_speed_10m,code:c.weather_code,time:c.time};RiskEngine.sources.weather="ok";App.health("weather","ok","Open-Meteo");this.renderWeather()}catch{RiskEngine.sources.weather="error";App.health("weather","error","Open-Meteo 無回應");this.renderWeather(true)}},
 async quake(){const s=StateCore.get();try{const j=await this.getJson("https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson",5000),arr=[];for(const f of j.features||[]){const p=f.properties||{},co=f.geometry?.coordinates||[],mag=Number(p.mag),lat=Number(co[1]),lon=Number(co[0]);if(!Number.isFinite(mag)||mag<3.5)continue;const d=App.distanceKm(s.lat,s.lon,lat,lon);if(d>1200)continue;const sev=(mag>=6.5&&d<=250)?"red":((mag>=5.5&&d<=500)||(mag>=4&&d<=80))?"orange":"green";arr.push({title:`M${mag.toFixed(1)} ${p.place||"地震"}`,summary:`距離約 ${Math.round(d)} 公里`,sev,url:p.url})}RiskEngine.quakes=arr.slice(0,10);RiskEngine.sources.quake="ok";App.health("quake","ok",`USGS ${RiskEngine.quakes.length} 筆`)}catch{RiskEngine.sources.quake="error";App.health("quake","error","USGS 無回應")}},
 async news(){const s=StateCore.get(),q=`${LOCATION_DATA[s.countryKey]?.en||s.country} (earthquake OR flood OR storm OR war OR conflict OR attack OR evacuation OR disaster OR emergency)`;return new Promise(resolve=>{const cb="gdeltCb_"+Date.now(),script=document.createElement("script");let done=false;const finish=()=>{if(done)return;done=true;try{delete window[cb]}catch{};script.remove();resolve()};const timer=setTimeout(()=>{RiskEngine.sources.news="error";App.health("news","error","GDELT 逾時");finish()},5000);window[cb]=j=>{clearTimeout(timer);RiskEngine.news=(j?.articles||j?.items||[]).slice(0,8);
       const titles=RiskEngine.news.map(x=>String(x.title||"").toLowerCase()).join(" ");
       if(/war|attack|shooting|explosion|evacuation|typhoon|earthquake|flood|tsunami|missile|conflict/.test(titles)){
         RiskEngine.sources.news="ok";
       }else{
         RiskEngine.sources.news="ok";
       }App.health("news","ok",`GDELT ${RiskEngine.news.length} 筆`);this.renderNews();finish()};script.onerror=()=>{clearTimeout(timer);RiskEngine.sources.news="error";App.health("news","error","GDELT 載入失敗");finish()};script.src=`https://api.gdeltproject.org/api/v2/doc/doc?query=${encodeURIComponent(q)}&mode=artlist&format=jsonp&maxrecords=8&timespan=24h&sort=datedesc&callback=${cb}`;document.head.appendChild(script)})},
 async refresh(){this.setStatus("背景更新中…");await Promise.allSettled([this.weather(),this.quake(),this.news()]);RiskEngine.evaluate();this.renderNews();App.renderHealth();this.setStatus(`更新完成 ${new Date().toLocaleTimeString("zh-TW",{hour:"2-digit",minute:"2-digit"})}`)},
 renderWeather(fail=false){const e=document.getElementById("weatherBox");if(!e)return;if(!RiskEngine.weather){e.innerHTML=`<div class="status">${fail?"天氣暫時無法取得":"背景讀取天氣中…"}</div>`;return}const w=RiskEngine.weather;e.innerHTML=`<div class="kpis"><div class="kpi"><span>氣溫</span><b>${w.temp}°C</b></div><div class="kpi"><span>體感</span><b>${w.feel}°C</b></div><div class="kpi"><span>降雨</span><b>${w.rain} mm</b></div><div class="kpi"><span>風速</span><b>${w.wind} km/h</b></div></div><div class="muted">Open-Meteo｜${w.time||""}</div>`},
 renderNews(){const e=document.getElementById("newsBox");if(!e)return;e.innerHTML=RiskEngine.news.length?RiskEngine.news.map(x=>`<div class="news-item"><a href="${x.url||x.link||"#"}" target="_blank" rel="noopener">${esc(x.title||"未命名新聞")}</a></div>`).join(""):`<div class="status">${RiskEngine.sources.news==="error"?"新聞來源目前異常，請直接查看官方旅遊警示。":"目前沒有取得重大新聞資料。"}</div>`},
 setStatus(t){document.querySelectorAll("[data-live-status]").forEach(e=>e.textContent=t)}
};
window.LiveEvents=LiveEvents;
