window.LOCAL_PHRASES={
 zhTW:{medical:"我需要醫療協助，請幫我叫救護車。",police:"我需要警察協助，請幫我報警。",followed:"有人正在跟蹤我，我感到不安全，請幫我聯絡警察。",accident:"我發生意外，需要協助。",passport:"我的護照遺失了，請告訴我該怎麼辦。",disaster:"這裡發生災害、衝突或重大緊急事件，我需要安全避難處和協助。"},
 zhHK:{medical:"我需要醫療協助，唔該幫我叫救護車。",police:"我需要警察幫手，唔該幫我報警。",followed:"有人跟住我，我覺得唔安全，唔該幫我報警。",accident:"我發生咗意外，需要幫手。",passport:"我本護照唔見咗，請問我應該點做？",disaster:"呢度發生災害、衝突或者重大緊急事故，我需要安全嘅避難地方同協助。"},
 ja:{medical:"医療の助けが必要です。救急車を呼んでください。",police:"警察の助けが必要です。警察を呼んでください。",followed:"誰かにつけられています。危険を感じています。警察を呼んでください。",accident:"事故に遭いました。助けが必要です。",passport:"パスポートをなくしました。どうすればいいですか。",disaster:"ここで災害、紛争、または重大な緊急事態が起きています。安全な避難場所と支援が必要です。"},
 de:{medical:"Ich brauche medizinische Hilfe. Bitte rufen Sie einen Krankenwagen.",police:"Ich brauche Hilfe von der Polizei. Bitte rufen Sie die Polizei.",followed:"Jemand verfolgt mich. Ich fühle mich nicht sicher. Bitte rufen Sie die Polizei.",accident:"Ich hatte einen Unfall und brauche Hilfe.",passport:"Ich habe meinen Reisepass verloren. Was soll ich tun?",disaster:"Hier gibt es eine Katastrophe, einen Konflikt oder einen schweren Notfall. Ich brauche einen sicheren Zufluchtsort und Hilfe."},
 fr:{medical:"J’ai besoin d’une aide médicale. Appelez une ambulance, s’il vous plaît.",police:"J’ai besoin de la police. Appelez la police, s’il vous plaît.",followed:"Quelqu’un me suit. Je ne me sens pas en sécurité. Appelez la police, s’il vous plaît.",accident:"J’ai eu un accident et j’ai besoin d’aide.",passport:"J’ai perdu mon passeport. Que dois-je faire ?",disaster:"Il y a une catastrophe, un conflit ou une urgence grave ici. J’ai besoin d’un lieu sûr et d’aide."},
 es:{medical:"Necesito ayuda médica. Por favor, llame a una ambulancia.",police:"Necesito ayuda de la policía. Por favor, llame a la policía.",followed:"Alguien me está siguiendo. No me siento seguro. Por favor, llame a la policía.",accident:"He tenido un accidente y necesito ayuda.",passport:"He perdido mi pasaporte. ¿Qué debo hacer?",disaster:"Aquí hay un desastre, un conflicto o una emergencia grave. Necesito un lugar seguro y ayuda."},
 en:{medical:"I need medical help. Please call an ambulance.",police:"I need the police. Please call the police.",followed:"Someone is following me. I do not feel safe. Please call the police.",accident:"I had an accident and need help.",passport:"I lost my passport. What should I do?",disaster:"There is a disaster, conflict, or major emergency here. I need a safe shelter and assistance."}
};
window.COUNTRY_LANGUAGE_PROFILE={HK:{phrase:"zhHK",voice:"zh-HK",label:"粵語"},MO:{phrase:"zhHK",voice:"zh-HK",label:"粵語"},TW:{phrase:"zhTW",voice:"zh-TW",label:"繁體中文"},JP:{phrase:"ja",voice:"ja-JP",label:"日文"},DE:{phrase:"de",voice:"de-DE",label:"德文"},FR:{phrase:"fr",voice:"fr-FR",label:"法文"},ES:{phrase:"es",voice:"es-ES",label:"西班牙文"},GB:{phrase:"en",voice:"en-GB",label:"英文"},US:{phrase:"en",voice:"en-US",label:"英文"},AU:{phrase:"en",voice:"en-AU",label:"英文"},CA:{phrase:"en",voice:"en-CA",label:"英文"}};
